# Generated by Django 4.1.2 on 2022-10-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productColor',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productSize',
        ),
        migrations.AddField(
            model_name='products',
            name='productColor',
            field=models.ManyToManyField(blank=True, to='products.colors'),
        ),
        migrations.AddField(
            model_name='products',
            name='productSize',
            field=models.ManyToManyField(blank=True, to='products.sizes'),
        ),
    ]
