# Generated by Django 4.1.2 on 2022-10-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_productcolor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
    ]
