# Generated by Django 4.1.2 on 2022-10-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_colors_color_rename_products_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productColor',
            field=models.ManyToManyField(blank=True, related_name='colors', to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productSize',
            field=models.ManyToManyField(blank=True, related_name='sizes', to='products.size'),
        ),
    ]
